name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push the Docker image
      run: |
        # Extract the version number from pyproject.toml using awk
        CURRENT_VERSION=$(awk -F '"' '/version =/ { print $2 }' pyproject.toml | head -n 1)
        docker buildx create --name mybuilder --use
        docker buildx build --platform linux/amd64,linux/arm64 --push -t hingstarne/memgpt-server:$CURRENT_VERSION -t hingstarne/memgpt-server:latest .
